services:
  kafka:
    ports:
      - ${EXTERNAL_PORT}:${EXTERNAL_PORT}
    environment:
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:${EXTERNAL_PROTOCOL:-PLAINTEXT}
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:${EXTERNAL_PORT}
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://${EXTERNAL_HOST}:${EXTERNAL_PORT}
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
