services:
  gitlab:
    container_name: gitlab
    image: ${IMAGE:-gitlab/gitlab-ce}:${TAG:-latest}
    volumes:
      - config:/etc/gitlab
      - data:/var/opt/gitlab
      - logs:/var/log/gitlab
    shm_size: ${SHM_SIZE:-256m}
    hostname: gitlab
    restart: unless-stopped

volumes:
  config:
  data:
  logs:
