version: "3.9"

services:
  qiandao:
    container_name: qiandao
    image: a76yyyy/qiandao:${TAG:-latest}
    volumes:
      - config:/usr/src/app/config
    env_file: .env
    restart: unless-stopped

volumes:
  config:

networks:
  default:
    name: qiandao
