version: "3.8"

services:
  zookeeper:
    container_name: zookeeper
    image: zookeeper:${TAG-latest}
    ports:
      - "2181:2181"
    volumes:
      - data:/data
      - log:/datalog
    hostname: zookeeper
    restart: unless-stopped

networks:
  default:
    name: zookeeper

volumes:
  data:
  log:
