services:
  confluence:
    container_name: atlassian_confluence
    image: atlassian/confluence:${CONFLUENCE_TAG:-latest}
    volumes:
      - confluence_data:/var/atlassian/application-data/confluence
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: ${TIMEZONE:-Asia/Shanghai}
      JVM_MINIMUM_MEMORY: ${CONFLUENCE_JVM_MINIMUM_MEMORY:-512m}
      JVM_MAXIMUM_MEMORY: ${CONFLUENCE_JVM_MAXIMUM_MEMORY:-2048m}
      ATL_TOMCAT_SECURE: ${CONFLUENCE_SECURE:-true}
      ATL_TOMCAT_SCHEME: ${CONFLUENCE_SCHEME:-https}
      ATL_PROXY_NAME: ${CONFLUENCE_DOMAIN}
      ATL_PROXY_PORT: ${CONFLUENCE_PORT:-443}
    hostname: confluence
    restart: unless-stopped

volumes:
  confluence_data:
