services:
  confluence:
    container_name: atlassian_confluence
    image: confluence-server:${CONFLUENCE_TAG:-latest}-multi-language-support
    build:
      context: optional/confluence
      dockerfile: multi-language-support.Dockerfile
      args:
        - UBUNTU_MIRROR
        - IMAGE=atlassian/confluence-server:${CONFLUENCE_TAG:-latest}
    volumes:
      - confluence_data:/var/atlassian/application-data/confluence
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: ${TIMEZONE:-Asia/Shanghai}
      JVM_MINIMUM_MEMORY: ${CONFLUENCE_JVM_MINIMUM_MEMORY:-512m}
      JVM_MAXIMUM_MEMORY: ${CONFLUENCE_JVM_MAXIMUM_MEMORY:-2048m}
      ATL_TOMCAT_SECURE: ${CONFLUENCE_SECURE:-true}
      ATL_TOMCAT_SCHEME: ${CONFLUENCE_SCHEME:-https}
      ATL_PROXY_NAME: ${CONFLUENCE_DOMAIN}
      ATL_PROXY_PORT: ${CONFLUENCE_PORT:-443}
    hostname: confluence
    restart: unless-stopped
    depends_on:
      - database

volumes:
  confluence_data:
