version: "3.8"

services:
  mysql:
    container_name: atlassian_mysql
    image: mysql:${MYSQL_TAG:-8}
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root
    secrets:
      - mysql_root
    hostname: mysql
    restart: unless-stopped

volumes:
  mysql_data:

secrets:
  mysql_root:
    file: ./secrets/mysql_root
