services:
  n8n:
    container_name: n8n
    image: n8nio/n8n:${TAG:-latest}
    volumes:
      - data:/home/node/.n8n
    env_file:
      - path: ./.env
        required: false
    environment:
      N8N_PROXY_HOPS: ${N8N_PROXY_HOPS:-1}
      N8N_PROTOCOL: ${N8N_PROTOCOL:-https}
      N8N_HOST: ${N8N_HOST:?N8N_HOST is required}
      N8N_WEBHOOK_URL: ${N8N_WEBHOOK_URL:-${N8N_PROTOCOL:-https}://${N8N_HOST:?N8N_HOST is required}/}
      N8N_EDITOR_BASE_URL: ${N8N_EDITOR_BASE_URL:-${N8N_PROTOCOL:-https}://${N8N_HOST:?N8N_HOST is required}}
      TZ: ${TZ:-Etc/UTC}
      GENERIC_TIMEZONE: ${GENERIC_TIMEZONE:-${TZ:-Etc/UTC}}
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
    hostname: n8n
    restart: unless-stopped
    healthcheck:
      test: [CMD, wget, -q, -O, /dev/null, "http://127.0.0.1:5678/healthz/readiness"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s

volumes:
  data:

networks:
  default:
    name: n8n
