version: "3.8"

services:
  sql-edge:
    image: ${REGISTRY:-mcr.microsoft.com/}azure-sql-edge:${TAG:-latest}
    volumes:
      - data:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD
      - MSSQL_PID
    hostname: sql-edge
    restart: unless-stopped

volumes:
  data:

networks:
  default:
    name: sql-edge
