version: "3.8"

services:
  authelia:
    container_name: authelia
    image: authelia/authelia:${TAG:-latest}
    volumes:
      - config:/config
    environment:
      TZ: ${TIMEZONE:-Asia/Shanghai}
    hostname: authelia
    restart: unless-stopped

volumes:
  config:

networks:
  default:
    name: authelia
