version: "3.8"

services:
  traefik:
    container_name: traefik
    image: traefik:${TAG:-latest}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - config:/etc/traefik
    hostname: traefik
    restart: unless-stopped

volumes:
  config:

networks:
  default:
    name: traefik
