version: "3.8"

services:
  metricbeat:
    container_name: metricbeat
    image: elastic/metricbeat:${TAG:-latest}
    volumes:
      - "${DOCKER_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock"
      - "/sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro"
      - "/proc:/hostfs/proc:ro"
      - "/:/hostfs:ro"
      - "./mount/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro"
    user: root
    hostname: metricbeat
    restart: unless-stopped

networks:
  default:
    name: metricbeat
