version: "3.8"

services:
  mssql:
    container_name: mssql
    image: ${REGISTRY:-mcr.microsoft.com/}mssql/server:${TAG:-latest}
    volumes:
      - data:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD
      - MSSQL_PID
    hostname: mssql
    restart: unless-stopped

volumes:
  data:

networks:
  default:
    name: mssql
