services:
  sub2api:
    container_name: sub2api
    image: weishaw/sub2api:${TAG:-latest}
    volumes:
      - data:/app/data
    environment:
      AUTO_SETUP: true
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 80
      SERVER_MODE: ${SERVER_MODE:-release}
      SERVER_FRONTEND_URL: ${SERVER_FRONTEND_URL:-}
      RUN_MODE: ${RUN_MODE:-standard}
      ADMIN_EMAIL: ${ADMIN_EMAIL:-admin@sub2api.local}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-}
      JWT_SECRET: ${JWT_SECRET:-}
      JWT_EXPIRE_HOUR: ${JWT_EXPIRE_HOUR:-24}
      TZ: ${TZ:-Asia/Shanghai}
      UPDATE_PROXY_URL: ${UPDATE_PROXY_URL:-}
    hostname: sub2api
    restart: unless-stopped

volumes:
  data:

networks:
  default:
    name: sub2api
