services:
  redapp:
    container_name: redapp
    image: ghcr.io/pmextra/redapp:${TAG:-latest}
    volumes:
      - data:/var/lib/redapp
    environment:
      REDAPP_PUBLIC_URL: ${REDAPP_PUBLIC_URL:-}
      REDAPP_TRUSTED_PROXIES: ${REDAPP_TRUSTED_PROXIES:-}
    read_only: true
    stop_grace_period: 30s
    hostname: redapp
    restart: unless-stopped

volumes:
  data:

networks:
  default:
    name: redapp
