services:
  redapp:
    container_name: redapp
    image: ghcr.io/pmextra/redapp:${TAG:-latest}
    volumes:
      - data:/var/lib/redapp
    env_file:
      - path: ./.env
        required: false
    read_only: true
    stop_grace_period: 30s
    hostname: redapp
    restart: unless-stopped

volumes:
  data:

networks:
  default:
    name: redapp
