version: "3.8"

services:
  dps:
    container_name: dps
    image: defreitas/dns-proxy-server:${TAG:-latest}
    ports:
      - "53:53/udp"
    volumes:
      - conf:/app/conf
      - /etc/resolv.conf:/etc/resolv.conf
      - /var/run/docker.sock:/var/run/docker.sock
    hostname: dps
    restart: unless-stopped

volumes:
  conf:

networks:
  default:
    name: dps
