services:
  postgres:
    image: localhost/build/postgres:${TAG:?Set TAG explicitly in postgres/.env to select a PostgreSQL version}
    build:
      context: ./build
      args:
        - TAG
        - DEBIAN_MIRROR
        - POSTGRESQL_PUB_MIRROR
        - INSTALL_PACKAGES
