version: "3.8"

services:
  mysql:
    container_name: mysql
    image: mysql:${TAG:-latest}
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_HOST
      - MYSQL_ROOT_USER
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    hostname: mysql
    restart: unless-stopped

volumes:
  data:

networks:
  default:
    name: mysql
