services:
  xray:
    container_name: xray
    image: ghcr.io/xtls/xray-core:${TAG:-latest}
    volumes:
      - config:/usr/local/etc/xray:ro
    hostname: xray
    restart: unless-stopped

volumes:
  config:

networks:
  default:
    name: xray
