version: "3.8"

services:
  xray:
    container_name: xray
    image: teddysun/xray:${TAG:-latest}
    volumes:
      - config:/etc/xray
    environment:
      XRAY_LOCATION_CONFDIR: /etc/xray
    hostname: xray
    restart: unless-stopped

volumes:
  config:

networks:
  default:
    name: xray
