version: "3.8"

services:
  xray:
    container_name: xray
    image: teddysun/xray:${TAG:-latest}
    volumes:
      - conf:/etc/xray
    environment:
      XRAY_LOCATION_CONFDIR: /etc/xray

volumes:
  conf:

networks:
  default:
    name: xray
