version: "3.8"

services:
  kafka:
    container_name: kafka
    image: bitnami/kafka:${TAG:-latest}
    volumes:
      - data:/bitnami/kafka
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    hostname: kafka
    restart: unless-stopped

volumes:
  data:

networks:
  default:
    name: kafka
