version: "3.8"

services:
  teleport:
    container_name: teleport
    image: quay.io/gravitational/teleport:${TAG:-latest}
    ports:
      - "3023:3023"
      - "3025:3025"
      - "3080:3080"
    volumes:
      - config:/etc/teleport
      - data:/var/lib/teleport

volumes:
  config:
  data:
